name: Build
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    strategy:
      fail-fast: false
      matrix:
        board:
          - bluemicro840_v1
          - nice_nano
        shield:
          - breeze_left
          - breeze_right
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (breeze Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=breeze_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Breeze DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: Breeze Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 breeze_left_nice_nano.uf2
      - name: Archive (Breeze Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: breeze_left_nice_nano.uf2
      - name: West Build (Breeze Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=breeze_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Breeze Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 breeze_right_nice_nano.uf2
      - name: Archive (Breeze Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: sofle_right_nice_nano.uf2
